In [1]:
import tensorflow as tf

Here we test the mask to select the rows for the bc conditions.

In [2]:
dataset = tf.stack([tf.range(0, 10), tf.range(10, 20)], axis=1)
print(dataset.shape)

(10, 2)


In [3]:
with tf.Session() as sess:
    print(sess.run(dataset))

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [22]:
bc_mask = tf.constant([[1], [5], [9]])
bc_set = tf.gather_nd(dataset, bc_mask)
with tf.Session() as sess:
    print(sess.run(dataset))
    print(sess.run(bc_set))


[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
[[ 1 11]
 [ 5 15]
 [ 9 19]]


In [19]:
bc_mask.shape

TensorShape([Dimension(3), Dimension(1)])

In [20]:
dataset.shape

TensorShape([Dimension(10), Dimension(2)])

# Using dynamic partitioning

In [4]:
bc_mask = tf.placeholder(dtype=tf.int32)

In [7]:
bc_set = tf.gather_nd(dataset, bc_mask)
with tf.Session() as sess:
    print(sess.run(dataset))
    print(sess.run(bc_set, feed_dict={bc_mask: [[1], [5], [9]]}))

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
[[ 1 11]
 [ 5 15]
 [ 9 19]]
